<a href="https://colab.research.google.com/github/OmkarJadhav2002/Python-Library-Numpy/blob/main/Copy_of_Task_13_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [5]:
# a1 = np.array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
# a1

# (np.arange(10) == 4).astype(int)
# or 
a1 = np.nan * np.arange(10)
a1[4] = 1
a1

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
a, b = map(int, input("Enter the size of array: ").split())

arr = np.random.random((a, b))
print(arr, '\n')

print("Mean of array: ", np.mean(arr))

Enter the size of array: 3 3 
[[0.82502715 0.34128076 0.8387332 ]
 [0.59608043 0.88539238 0.09083831]
 [0.64132531 0.39598617 0.10082316]] 

Mean of array:  0.5239429838532366


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-

```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [10]:
def func(a, b):
  arr = np.ones((a, b)).astype(int)
  arr[1:-1, 1:-1] = 0
  return arr

func(4, 5)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [13]:
arr2 = np.linspace(0, 1, 12)[1:-1]
arr2

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [16]:
# NO, You can't create an array of non-square shape
print(np.eye(4), '\n')
print(np.identity(3), '\n')

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [19]:
# arr3 = np.linspace(0, 4, 25)
# arr3
# or
arr3 = np.zeros((5, 5))
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectors from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


In [24]:
# arr4 = np.linspace(1, 100, 20).reshape(10, 2)
arr4 = np.random.randint(1, 100, (10, 2))
arr = np.array([2, 3])
print(arr4, '\n')
print(arr)

np.sqrt(np.sum((arr4-arr) ** 2, axis=1)).astype(int)

[[19 96]
 [45 18]
 [73 43]
 [94 27]
 [92 24]
 [97 57]
 [32 74]
 [91 72]
 [45 75]
 [20 67]] 

[2 3]


array([ 94,  45,  81,  95,  92, 109,  77, 112,  83,  66])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [28]:
#Code here
arr = np.zeros((6, 7, 8))
print(arr, '\n')
np.unravel_index(100, (6, 7, 8))

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0

(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [35]:
# arr4 = np.array([1, 2, 3, 4, -8, -10])
user_input = input().strip().split()
np.array(user_input[::-1]).astype(float)

1 2 3 4 5 


array([5., 4., 3., 2., 1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [36]:
arr5 = np.array([1, 2, 3, 4, 5])
# count = 0
# for i in range(len(arr5)):
#   count += 1

# print(count)
np.size(arr5)

5

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [43]:
# arr6 = np.random.random(10)
arr6 = np.random.randint(1, 100, (10, 2))
# arr6 = np.array([86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318])
print(arr6, '\n') 

def softmax(arr):
  if type(arr) != np.ndarray:
    raise TypeError("Requires np array.")
  elif arr.ndim > 1:
    raise TypeError("Requires 1D array.")
  else:
    return np.exp(arr)/np.sum(np.exp(arr))

softmax(arr6)

[[16 31]
 [41 95]
 [35 98]
 [63 70]
 [29 37]
 [95  7]
 [40 21]
 [73 62]
 [34 68]
 [19 36]] 



TypeError: ignored

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [45]:
# def ver_stack(arr1, arr2, arr3):
def ver_stack(*args):
  if type(arr1) != np.ndarray or type(arr2) != np.ndarray or type(arr3) != np.ndarray:
    raise TypeError("Requires np array.")
  else:
    return np.vstack((arr1, arr2, arr3))
# arr3
arr1 = np.arange(10).reshape(2, 5)
arr2 = np.arange(10).reshape(2, 5)
arr3 = np.random.random(10).reshape(2, 5)
ver_stack(arr1, arr2, arr3)

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [0.46926457, 0.41877614, 0.34708155, 0.51244439, 0.87125528],
       [0.57365804, 0.78604412, 0.22248119, 0.80691882, 0.05086113]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [62]:
def date_array(start: str, end: str):
  if type(start) != str or type(end) != str:
    raise TypeError

  total_days_of_months = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30, "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}

  
  end = end.split('-')
  end_last = int(end[-1]) + 1 # incrementing the date

  if total_days_of_months[end[-2]] < end_last:
    days_diff = end_last - total_days_of_months[[-2]]
    end[-1] = f'0{days_diff}' if days_diff else f'{days_diff}'
    next_month = int(end[-2]) + 1

  
  end[-1] = f'0{end_last}' if int(end_last) < 10 else f'{end_last}'
  print(end)
  end = '-'.join(end)
  return np.arange(start, end, dtype="datetime64[D]")

date_array(start = '2022-11-01', end = '2022-11-30')

TypeError: ignored

###`Q-14:` Subtract the mean of each row from a matrix.

In [70]:
arr = np.random.random((5, 4))
print(arr, '\n')
m = np.mean(arr, axis=1, keepdims=True)
print(m, '\n')
arr - m

[[0.92354536 0.1664312  0.05848077 0.71632006]
 [0.57142307 0.84560759 0.27654534 0.53430355]
 [0.5214053  0.77469051 0.77054976 0.08038015]
 [0.90496132 0.71142673 0.46173925 0.25187321]
 [0.78077162 0.10810459 0.91079811 0.87886564]] 

[[0.46619435]
 [0.55696989]
 [0.53675643]
 [0.58250013]
 [0.66963499]] 



array([[ 0.45735101, -0.29976314, -0.40771357,  0.25012571],
       [ 0.01445319,  0.2886377 , -0.28042454, -0.02266634],
       [-0.01535113,  0.23793408,  0.23379333, -0.45637628],
       [ 0.32246119,  0.12892661, -0.12076088, -0.33062692],
       [ 0.11113663, -0.5615304 ,  0.24116312,  0.20923065]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [83]:
#Code here
arr5 = np.arange(20).reshape(5, 4).astype(int)
print(arr5, '\n')

arr5[:, [0, 3, 1]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 



array([[ 0,  3,  1],
       [ 4,  7,  5],
       [ 8, 11,  9],
       [12, 15, 13],
       [16, 19, 17]])

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
arr = np.arange(20).reshape(5, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [84]:
np.where(arr%2!=0, -1, arr)

array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1],
       [12, -1, 14, -1],
       [16, -1, 18, -1]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

In [93]:
a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])

print(b > a)
print(a < b)

print(a[b > a])
print(b[a < b])

a[b > a] = b[a < b]
a

[False False False  True False]
[False False False  True False]
[5]
[7]


array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[8650,  528, 4137, 6058, 3494],
       [  18, 8481, 8606, 3056, 2599],
       [7478,  401, 6872,  115, 7899],
       [ 859, 6308, 7893, 9897, 9998],
       [1012, 9182, 7232, 6104, 4475],
       [7726, 1545, 2985, 2217, 6794],
       [  74, 7063, 8585,  260, 1883],
       [9242, 7793, 7271, 2389,  492]])

In [ ]:
arr1[:, ::2]

array([[8650, 4137, 3494],
       [  18, 8606, 2599],
       [7478, 6872, 7899],
       [ 859, 7893, 9998],
       [1012, 7232, 4475],
       [7726, 2985, 6794],
       [  74, 8585, 1883],
       [9242, 7271,  492]])

In [ ]:
# Normalise the array
m1 = np.min(arr1)
m2 = np.max(arr1)
print(m1)
print(m2)

normalize = (arr1 - m1)/(m2-m1)
print("Normalized array: ")
print(normalize)

18
9998
Normalized array: 
[[0.86492986 0.0511022  0.41272545 0.60521042 0.34829659]
 [0.         0.84799599 0.86052104 0.30440882 0.25861723]
 [0.74749499 0.03837675 0.68677355 0.00971944 0.78967936]
 [0.08426854 0.63026052 0.78907816 0.98987976 1.        ]
 [0.0995992  0.91823647 0.72284569 0.60981964 0.44659319]
 [0.77234469 0.15300601 0.29729459 0.22034068 0.67895792]
 [0.00561122 0.70591182 0.85841683 0.0242485  0.18687375]
 [0.9242485  0.77905812 0.72675351 0.23757515 0.04749499]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [99]:
np.random.seed(42)
arr1 = np.random.randint(0, 100, 12)
print(arr1)

def find_num(arr, num):
  arr = np.sort(arr)  # sort the array
  print("Sorted array: ", arr)
  print("Largest element at position {}".format(num), "is: ")
  for i in range(len(arr)):
    if num > len(arr):
      raise IndexError("Number if out of index/limit")
    elif num == 1:
      return arr[-1]
    else:
      return arr[-num]

find_num(arr1, 5)

[51 92 14 71 60 20 82 86 74 74 87 99]
Sorted array:  [14 20 51 60 71 74 74 82 86 87 92 99]
Largest element at position 5 is: 


82

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [113]:
a = np.array([1,2,3])
print(a)

print(np.repeat(a, 3))
print(np.tile(a, 3))

np.hstack([np.repeat(a, 3), np.tile(a, 3)])

[1 2 3]
[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])