<a href="https://colab.research.google.com/github/OmkarJadhav2002/Python-Library-Numpy/blob/main/NumPy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


In [1]:
import numpy as np

See examples:
```
arr = 
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [17]:
np.random.seed(42)
arr = np.random.randint(0, 100, (4, 3))
print("Given arraY:\n", arr, '\n')

# 1
print("Sorted array:\n", np.sort(arr), '\n')

# 2
print("Sorting based on second column:\n", arr[np.argsort(arr[:, 1])], '\n')
# or
# arr[arr[:, 1].argsort()]

# 3
res = np.array(sorted(arr, key = lambda x: max(x)))
print("Sorting the matrix based on max value in each row:\n", res)

# 4
print("\nSorting based on elements:\n", np.sort(arr, axis=None).reshape(4, 3))

Given arraY:
 [[51 92 14]
 [71 60 20]
 [82 86 74]
 [74 87 99]] 

Sorted array:
 [[14 51 92]
 [20 60 71]
 [74 82 86]
 [74 87 99]] 

Sorting based on second column:
 [[71 60 20]
 [82 86 74]
 [74 87 99]
 [51 92 14]] 

Sorting the matrix based on max value in each row:
 [[71 60 20]
 [82 86 74]
 [51 92 14]
 [74 87 99]]

Sorting based on elements:
 [[14 20 51]
 [60 71 74]
 [74 82 86]
 [87 92 99]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [49]:
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

extra_subject = np.array([41, 87, 72, 36, 92]).reshape(-1, 1)
# print(extra_subject)

# 1
new_marks1 = np.concatenate([marks, extra_subject], axis=1)
print("New array after adding the extra subjects marks:\n", new_marks1)

# 2
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1, -1)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1, -1)

new_marks2 = np.concatenate([new_marks1, rec1, rec2], axis=0)
print("\nNew array after adding the marks of new students:\n", new_marks2)

# 3
sum_of_sub = np.sum(new_marks2, axis=1, keepdims=True)
new_marks3 = np.concatenate([new_marks2, sum_of_sub], axis=1)
print("\nNew array after adding the total sum column:\n", new_marks3)

# 4
new_marks4 = np.array(sorted(new_marks3, key = lambda x: x[-1], reverse=True))[:2, :]
print("\nSorted array based on last column:\n", new_marks4)

New array after adding the extra subjects marks:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]

New array after adding the marks of new students:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]

New array after adding the total sum column:
 [[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]

Sorted array based on last column:
 [[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
# arr = np.random.randint(1, 10, 20).reshape(5, 4)
# arr

arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

print("Unique Row-wise:\n", np.unique(arr, axis=0), '\n')
print("Unique Column-wise:\n", np.unique(arr, axis=1), '\n')

Unique Row-wise:
 [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]] 

Unique Column-wise:
 [[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]] 



###`Q-4:` Flip given 2-D array along both axes at the same time.

In [50]:
arr = np.random.randint(1, 20, 20).reshape(5, 4)
print(arr, '\n')

# np.flip(arr, axis=None)
np.flip(arr, axis=[0, 1])

[[ 8  3  2 12]
 [ 6  2  1 12]
 [12 17 10 16]
 [15 15 19 12]
 [ 3  5 19  7]] 



array([[ 7, 19,  5,  3],
       [12, 19, 15, 15],
       [16, 10, 17, 12],
       [12,  1,  2,  6],
       [12,  2,  3,  8]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]] 

X = 6
```

In [ ]:
# code here
arr = np.array([[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]]) 

np.where(np.any(arr>6, axis=1))  # np.any()

(array([1, 3]),)

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [52]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [53]:
# code here
np.concatenate([arr1, arr2, arr3])

# or 
# arr = np.random.randint(0, 100, 20).reshape(5, 4)
# print(arr)

# print("\n2D array converted to 1D array: ")
# arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [64]:
# code here
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print(arr)

m1 = arr.argmax()
m2 = arr.argmin()

print("\nMaximum element position: ", m1)
print("Minimum element position: ", m2)

print("Maximum element: ", arr.max())
print("Minimum element: ", arr.min())

print("\nNew array:")
arr = np.delete(arr, m1, axis=1)
arr = np.delete(arr, m2, axis=1)
print(arr)
print("New max element: ", arr.max())
print("New min element: ", arr.min())

[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]

Maximum element position:  102
Minimum element position:  66
Maximum element:  998
Minimum element:  103

New array:
[[448 563 418 240 507 362 345 236 719 291 298 639 458 38

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 200]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [65]:
# code here
arr = np.random.randint(100, 700, 50).reshape(10, 5)
print(arr)

new_arr = np.clip(arr, a_min=100, a_max=200)
print("\nNew array:\n", new_arr)

print("\nCumulative Sum: ")
np.cumsum(new_arr)

[[505 381 689 427 478]
 [573 483 394 401 223]
 [644 249 392 454 524]
 [282 632 300 646 249]
 [574 157 411 133 609]
 [340 649 456 632 544]
 [413 131 544 232 482]
 [410 532 471 405 100]
 [674 218 153 146 261]
 [669 454 367 661 564]]

New array:
 [[200 200 200 200 200]
 [200 200 200 200 200]
 [200 200 200 200 200]
 [200 200 200 200 200]
 [200 157 200 133 200]
 [200 200 200 200 200]
 [200 131 200 200 200]
 [200 200 200 200 100]
 [200 200 153 146 200]
 [200 200 200 200 200]]

Cumulative Sum: 


array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000, 2200,
       2400, 2600, 2800, 3000, 3200, 3400, 3600, 3800, 4000, 4200, 4357,
       4557, 4690, 4890, 5090, 5290, 5490, 5690, 5890, 6090, 6221, 6421,
       6621, 6821, 7021, 7221, 7421, 7621, 7721, 7921, 8121, 8274, 8420,
       8620, 8820, 9020, 9220, 9420, 9620])

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [66]:
# code here
np.random.seed(42)
arr = np.random.random((5, 4))
print(arr)

new_arr = np.round(arr, 3)
print("\nNew array:\n", new_arr)

# 1
zeroth_perc = np.percentile(new_arr, 0)
print("\n0th Percentile: ", zeroth_perc)

min_ele = np.min(new_arr)
print("Minimum value in array: ", min_ele)
print(zeroth_perc==min_ele)

# 2
hun_perc = np.percentile(new_arr, 100)
print("\n100th percentile: ", hun_perc)

max_ele = np.max(new_arr)
print("Maximum value in array: ", max_ele)
print(hun_perc == max_ele)

# 3.
fif_perc = np.percentile(new_arr, 50)
fifone_perc = np.percentile(new_arr, 51)
print("\n50th percentile: ", fif_perc)
print("51th percentile: ", fifone_perc)
print("Difference: ", fifone_perc-fif_perc)

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]]

New array:
 [[0.375 0.951 0.732 0.599]
 [0.156 0.156 0.058 0.866]
 [0.601 0.708 0.021 0.97 ]
 [0.832 0.212 0.182 0.183]
 [0.304 0.525 0.432 0.291]]

0th Percentile:  0.021
Minimum value in array:  0.021
True

100th percentile:  0.97
Maximum value in array:  0.97
True

50th percentile:  0.40349999999999997
51th percentile:  0.41433
Difference:  0.010830000000000006
